<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FitnessTracking.Domain\FitnessTracking.Domain.csproj" />
      <ProjectReference Include="..\FitnessTracking.Shared\FitnessTracking.Shared.csproj" />
    </ItemGroup>

</Project>
