services:
  fitnesstrackingdb:
    container_name: fitnesstrackingdb
    environment:
      - POSTGRES_USER=${FITNESSTRACKING_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FITNESSTRACKING_POSTGRES_PASSWORD}
      - POSTGRES_DB=${FITNESSTRACKING_POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - fitness-tracking-postgres-data:/var/lib/postgresql

  fitnesstracking.api:
    container_name: fitnesstracking.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__FitnessTrackingDbContext=Server=fitnesstrackingdb;Port=5432;Database=${FITNESSTRACKING_POSTGRES_DB};Username=${FITNESSTRACKING_POSTGRES_USER};Password=${FITNESSTRACKING_POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/:/home/app/.microsoft/usersecrets
