services:
  fitnesstrackingdb:
    image: postgres:18

  fitnesstracking.api:
    image: fitnesstracking.api
    build:
      context: .
      dockerfile: FitnessTracking.Api/Dockerfile

volumes:
  fitness-tracking-postgres-data:
