// <auto-generated />
using System;
using System.Collections.Generic;
using FitnessTracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessTracking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FitnessTrackingDbContext))]
    [Migration("20260321104508_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracking.Domain.Models.Workout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<List<string>>("ProgressPhotos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessTracking.Domain.Models.Workout", b =>
                {
                    b.OwnsMany("FitnessTracking.Domain.Models.Exercise", "Exercises", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("WorkoutId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkoutId");

                            b1.ToTable("Exercise");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");

                            b1.OwnsMany("FitnessTracking.Domain.Models.Set", "Sets", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("ExerciseId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Reps")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Weight")
                                        .HasColumnType("double precision");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExerciseId");

                                    b2.ToTable("Set");

                                    b2.WithOwner()
                                        .HasForeignKey("ExerciseId");
                                });

                            b1.Navigation("Sets");
                        });

                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
